name: "infra"

on:
 push:
  branchs:
   -main
  paths:
   -10_infra/**
   -github/workflows/**
  workflow_dispatch:

permissions:
 id-token: write
 contents: read

jobs:
 previes:
  name: "Preview"
  runs-on: ubuntu-latest
  steps:
   - run: |
      echo "Hello World !"
